[package]
name = "microslop_groups_extract"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
reqwest = { version = "0.13.4", features = ["charset", "gzip", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
turso = "0.7.2"
